import {
  BrainCircuit,
  CheckCircle2,
  Images,
  Layers,
  Sparkles,
  Wand2,
} from "lucide-react";
import Image from "next/image";
import { Link } from "@/i18n/routing";
import PromptJumpForm from "./PromptJumpForm";
export { metadata } from "./metadata";

type ShowcaseImage = {
  id: string;
  src: string;
  alt: string;
  width: number;
  height: number;
};

type EditorialBlock = {
  id: string;
  eyebrow: string;
  title: string;
  description: string;
  image: ShowcaseImage;
};

const GPT2_SHOWCASE_IMAGES: ShowcaseImage[] = [
  {
    id: "gpt2-showcase-01",
    src: "/gpt2/gpt2-amalfi-coast-vintage-travel-poster.webp",
    alt: "gpt2 amalfi coast vintage travel poster example image",
    width: 896,
    height: 1200,
  },
  {
    id: "gpt2-showcase-02",
    src: "/gpt2/gpt2-boston-spring-2026-poster.webp",
    alt: "gpt2 boston spring 2026 poster design example",
    width: 768,
    height: 1376,
  },
  {
    id: "gpt2-showcase-03",
    src: "/gpt2/gpt2-anime-movie-poster-concept.webp",
    alt: "gpt2 anime movie poster concept visual sample",
    width: 1024,
    height: 1536,
  },
  {
    id: "gpt2-showcase-04",
    src: "/gpt2/gpt2-science-infographic-design.webp",
    alt: "gpt2 science infographic design output example",
    width: 1024,
    height: 1536,
  },
  {
    id: "gpt2-showcase-05",
    src: "/gpt2/gpt2-japanese-night-kimono-portrait.webp",
    alt: "gpt2 japanese night kimono portrait sample",
    width: 1024,
    height: 1024,
  },
  {
    id: "gpt2-showcase-06",
    src: "/gpt2/gpt2-action-camera-product-showcase.webp",
    alt: "gpt2 action camera product showcase render",
    width: 1280,
    height: 725,
  },
  {
    id: "gpt2-showcase-07",
    src: "/gpt2/gpt2-anna-magic-pen-illustration.webp",
    alt: "gpt2 anna magic pen illustration sample",
    width: 1024,
    height: 1536,
  },
  {
    id: "gpt2-showcase-08",
    src: "/gpt2/gpt2-creative-market-event-poster.webp",
    alt: "gpt2 creative market event poster example",
    width: 1280,
    height: 725,
  },
];

const GPT2_SHOWCASE_LOOP: ShowcaseImage[] = [
  ...GPT2_SHOWCASE_IMAGES,
  ...GPT2_SHOWCASE_IMAGES,
];

const GPT2_EDITORIAL_LIBRARY: EditorialBlock[] = [
  {
    id: "editorial-01",
    eyebrow: "Product Page",
    title: "Detail-first visual storytelling for product launches",
    description:
      "Use this module when you need premium product detail pages with clear hierarchy, conversion-focused layout, and polished brand consistency.",
    image: {
      id: "editorial-image-01",
      src: "/gpt2/MacBook Pro\u4ea7\u54c1\u8be6\u60c5\u9875.png",
      alt: "MacBook Pro style product detail page generated by gpt2",
      width: 1024,
      height: 1536,
    },
  },
  {
    id: "editorial-02",
    eyebrow: "Lifestyle Scene",
    title: "Natural group moments with authentic atmosphere",
    description:
      "Great for social and lifestyle campaigns where emotion, environment, and character interaction need to feel real and cinematic.",
    image: {
      id: "editorial-image-02",
      src: "/gpt2/\u4fbf\u5229\u5e97\u95e8\u53e3\u591c\u666f\u5408\u5f71.png",
      alt: "Night convenience store group photo style generated by gpt2",
      width: 1536,
      height: 1024,
    },
  },
  {
    id: "editorial-03",
    eyebrow: "Portrait Quality",
    title: "High-fidelity portrait framing for creator content",
    description:
      "Ideal for creator thumbnails, stream covers, and profile campaigns with strong subject separation and clean tonal control.",
    image: {
      id: "editorial-image-03",
      src: "/gpt2/\u5218\u4ea6\u83f2\u76f4\u64ad\u622a\u56fe.png",
      alt: "Livestream portrait screenshot style generated by gpt2",
      width: 1088,
      height: 1920,
    },
  },
  {
    id: "editorial-04",
    eyebrow: "Character Style",
    title: "Anime character outputs with expressive details",
    description:
      "Best for stylized campaigns that need clear character emotion, readable composition, and vibrant but controlled color depth.",
    image: {
      id: "editorial-image-04",
      src: "/gpt2/\u94f6\u53d1\u84dd\u773c\u52a8\u6f2b\u5973\u5b69\u8868\u60c5\u5305.png",
      alt: "Silver hair blue eyes anime character visual generated by gpt2",
      width: 1024,
      height: 1024,
    },
  },
];

const FAQ_ITEMS = [
  {
    question: "What is GPT Image 2?",
    answer:
      "GPT Image 2 is OpenAI’s image generation model used in ChatGPT Images 2.0 workflows. If your goal is campaign-ready output, it is mainly used for prompt accuracy, stronger visual consistency, and cleaner text-in-image results.",
  },
  {
    question: "How is GPT Image 2 different from GPT Image 1.5?",
    answer:
      "For most users, the practical difference is workflow quality: GPT Image 2 usually gives better prompt-following, more stable typography, and fewer retries before reaching production quality. The best way to confirm is testing both models with the same prompt set.",
  },
  {
    question: "How does GPT Image 2 compare to Nano Banana Pro?",
    answer:
      "Use-case fit matters more than brand names. If you care about ad-ready visuals, test both on the same tasks: hero banner, product detail image, and social post. Keep whichever gives better readability, style consistency, and iteration speed.",
  },
  {
    question: "Can I use GPT Image 2 for commercial work?",
    answer:
      "You can use outputs for commercial workflows only when your account plan and terms allow it. Before launch, always verify usage rights, brand policy, and model-output compliance for your target market.",
  },
  {
    question: "Can GPT Image 2 render text in non-English languages?",
    answer:
      "Yes, and this is a common reason people choose ChatGPT Images 2.0. For better multilingual text rendering, specify language, font tone, line breaks, and exact text blocks directly in the prompt.",
  },
  {
    question: "Can I edit existing images with GPT Image 2?",
    answer:
      "Yes. A practical flow is: upload a base image, define what must stay unchanged, then describe exactly what to edit (subject, background, typography, or lighting). This keeps revisions controllable for design and marketing teams.",
  },
  {
    question: "Does GPT Image 2 work with other Higgsfield tools?",
    answer:
      "In most creator workflows, yes through asset handoff. You can generate with GPT Image 2, then move images and prompt notes into your other tools for animation, compositing, or publishing.",
  },
  {
    question: "How do I get started?",
    answer:
      "Start with one clear business goal, generate a first draft, then iterate with constraints (style, text, composition, format). On this page, use the generator entry and the image-to-prompt tool to speed up your first production-ready set.",
  },
];

export default function ChatgptImagesTwoPage() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_ITEMS.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };

  const howToJsonLd = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to build campaign visuals with ChatGPT Images 2.0 and GPT image 2",
    step: [
      {
        "@type": "HowToStep",
        name: "Write your goal prompt",
        text: "Define target visual outcome and business use case in the input panel.",
      },
      {
        "@type": "HowToStep",
        name: "Generate and refine",
        text: "Run generation, improve typography, style consistency, and composition in quick iterations.",
      },
      {
        "@type": "HowToStep",
        name: "Fill campaign slots",
        text: "Replace each placeholder slot with final outputs and keep visual consistency across sections.",
      },
    ],
  };

  const softwareJsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "ChatGPT Images 2.0 Prompt Tool for GPT Image 2",
    applicationCategory: "DesignApplication",
    operatingSystem: "Web",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    description:
      "Tool page for prompt planning, visual slot design, and generator-ready execution.",
  };

  const webPageJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "ChatGPT Images 2.0 / GPT image 2 workflow page",
    url: "https://genanime.art/gpt-2",
    description:
      "Answer-first workflow page for ChatGPT Images 2.0 and GPT image 2 prompt planning, generation, and campaign slot execution.",
    inLanguage: "en",
  };

  return (
    <main className="min-h-screen bg-[#030305] pb-24 pt-24 text-zinc-200">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }}
      />

      <section className="relative overflow-hidden pb-8">
        <div className="pointer-events-none absolute left-1/2 top-0 h-[440px] w-[900px] -translate-x-1/2 rounded-full bg-indigo-500/10 blur-[140px]" />
        <div className="relative z-10 mx-auto w-full px-4 sm:px-6 md:px-10">
          <div className="mx-auto max-w-5xl text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-1.5 text-xs font-medium tracking-wide text-zinc-300">
              <Sparkles className="h-3.5 w-3.5 text-indigo-300" />
              GPT image 2 workflow
            </span>

            <h1 className="mt-6 text-balance text-4xl font-semibold leading-[1.02] tracking-tight text-white md:text-6xl">
              ChatGPT Images 2.0
              <br />
              from prompt to
              <span className="bg-gradient-to-r from-indigo-300 via-purple-300 to-pink-300 bg-clip-text text-transparent">
                {" "}
                campaign-ready
              </span>
            </h1>

            <p className="mx-auto mt-6 max-w-4xl text-base leading-relaxed text-zinc-400 md:text-[1.65rem] md:leading-relaxed">
              Build posters, product shots, social creatives, and multilingual
              signage with a practical GPT image 2 workflow. Start with prompt
              intent, then ship campaign assets faster.
            </p>
          </div>

          <div className="mx-auto mt-10 max-w-5xl">
            <PromptJumpForm />
          </div>
        </div>
      </section>

      <section className="mt-4 overflow-hidden">
        <div className="w-full">
          <div className="overflow-hidden [mask-image:linear-gradient(to_right,transparent,black_10%,black_90%,transparent)]">
            <div className="gpt2-marquee-track flex w-max items-center gap-4 px-2 md:gap-5 md:px-5">
              {GPT2_SHOWCASE_LOOP.map((image, index) => (
                <figure
                  key={`${image.id}-${index}`}
                  className="shrink-0 overflow-hidden rounded-2xl border border-white/10 bg-[#0a0b10]/80"
                >
                  <Image
                    src={image.src}
                    alt={image.alt}
                    width={image.width}
                    height={image.height}
                    sizes="(max-width: 640px) 220px, (max-width: 1024px) 300px, 360px"
                    className="h-[166px] w-auto max-w-none object-cover md:h-[214px]"
                    loading={index < GPT2_SHOWCASE_IMAGES.length ? "eager" : "lazy"}
                    priority={index < 3}
                  />
                </figure>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto mt-16 w-full max-w-5xl px-4 sm:px-6 md:px-10">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {[
            {
              title: "Prompt Compliance",
              text: "High-intent users want outputs that match prompt constraints on first try.",
            },
            {
              title: "Typography in Images",
              text: "ChatGPT Images 2.0 and GPT image 2 queries often focus on readable text rendering.",
            },
            {
              title: "Campaign Throughput",
              text: "Users compare workflow speed: idea, prompt, variation, final asset delivery.",
            },
            {
              title: "Cross-format Consistency",
              text: "Real-world demand includes cohesive outputs for hero, social, and ad placements.",
            },
          ].map((item) => (
            <article
              key={item.title}
              className="rounded-2xl border border-white/10 bg-[#090a10]/75 p-5 backdrop-blur-sm transition-colors hover:border-white/20"
            >
              <h3 className="text-sm font-semibold tracking-wide text-zinc-100">
                {item.title}
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-zinc-400">{item.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="mx-auto mt-14 w-full max-w-5xl px-4 sm:px-6">
        <div className="mb-7 flex flex-wrap items-end justify-between gap-4">
          <div className="max-w-2xl">
            <h2 className="text-2xl font-medium tracking-tight text-white md:text-3xl">
              Campaign Slot Library with Prompt Blueprints
            </h2>
            <p className="mt-2 text-sm leading-relaxed text-zinc-400 md:text-base">
              Four newly added visuals are now used as polished image-text modules
              for production-ready page sections.
            </p>
          </div>
          <span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/20 px-3 py-1.5 text-xs font-medium text-zinc-300">
            <Images className="h-4 w-4" />4 editorial blocks
          </span>
        </div>

        <div className="space-y-5 md:space-y-6">
          {GPT2_EDITORIAL_LIBRARY.map((block, index) => {
            const isOdd = index % 2 === 1;
            return (
              <article
                key={block.id}
                className="group grid items-center gap-5 overflow-hidden rounded-2xl border border-white/10 bg-[#08090d]/75 p-4 transition-colors duration-300 hover:border-white/20 md:grid-cols-2 md:gap-8 md:p-6"
              >
                <div className={isOdd ? "md:order-2" : "md:order-1"}>
                  <div className="relative aspect-[5/4] w-full overflow-hidden rounded-xl border border-white/10 bg-[#07080c]">
                    <Image
                      src={block.image.src}
                      alt={block.image.alt}
                      fill
                      sizes="(max-width: 768px) 100vw, 50vw"
                      className="object-cover object-center transition-transform duration-500 group-hover:scale-[1.015]"
                    />
                  </div>
                </div>

                <div className={isOdd ? "md:order-1" : "md:order-2"}>
                  <span className="inline-flex text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-400">
                    {block.eyebrow}
                  </span>
                  <h3 className="mt-2 text-xl font-medium leading-snug text-white md:text-[1.75rem]">
                    {block.title}
                  </h3>
                  <div className="mt-4 h-px w-12 bg-white/15" />
                  <p className="mt-4 max-w-[46ch] text-sm leading-relaxed text-zinc-400 md:text-base">
                    {block.description}
                  </p>
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <section className="mx-auto mt-14 w-full max-w-5xl px-4 sm:px-6 md:px-10">
        <div className="grid gap-6 lg:grid-cols-3">
          <div className="rounded-2xl border border-white/10 bg-[#090a10]/75 p-6 lg:col-span-2 md:p-7">
            <h2 className="text-[1.65rem] font-medium tracking-tight text-white">
              GPT image 2 Prompt Architecture
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-zinc-300 md:text-base">
              Answer first: for production use, start from business goal and output format,
              then lock subject, style, and typography constraints before generation.
            </p>
            <div className="mt-5 space-y-4">
              {[
                "Task layer: define exact use case (poster, ad, product, social).",
                "Subject layer: who or what appears and where focal point sits.",
                "Style layer: visual direction, material quality, and color discipline.",
                "Control layer: typography requirements, composition constraints, and output format.",
                "Validation layer: check legibility, brand fit, and conversion readiness.",
              ].map((step, index) => (
                <div
                  key={step}
                  className="flex items-start gap-3 border-b border-white/10 pb-3 last:border-b-0 last:pb-0"
                >
                  <CheckCircle2 className="mt-0.5 h-5 w-5 text-zinc-300" />
                  <p className="text-sm leading-relaxed text-zinc-300">
                    <span className="font-semibold text-white">Step {index + 1}:</span> {step}
                  </p>
                </div>
              ))}
            </div>
            <div className="mt-6 overflow-hidden rounded-xl border border-white/10">
              <table className="w-full text-left text-xs md:text-sm">
                <thead className="bg-white/[0.03] text-zinc-300">
                  <tr>
                    <th className="px-3 py-2 font-medium">Use Case</th>
                    <th className="px-3 py-2 font-medium">Prompt Focus</th>
                    <th className="px-3 py-2 font-medium">Output Priority</th>
                  </tr>
                </thead>
                <tbody className="text-zinc-400">
                  {[
                    ["Landing Hero", "Visual hierarchy + headline-safe space", "CTR-ready first screen"],
                    ["Product Page", "Material details + controlled reflections", "Commercial clarity"],
                    ["Social Creative", "Readable typography + fast variants", "High iteration speed"],
                  ].map((row) => (
                    <tr key={row[0]} className="border-t border-white/10">
                      <td className="px-3 py-2">{row[0]}</td>
                      <td className="px-3 py-2">{row[1]}</td>
                      <td className="px-3 py-2">{row[2]}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <aside className="rounded-2xl border border-white/10 bg-[#090a10]/75 p-6">
            <h3 className="flex items-center gap-2 text-lg font-semibold text-white">
              <BrainCircuit className="h-5 w-5 text-zinc-300" />
              Start Here
            </h3>
            <p className="mt-3 text-sm leading-relaxed text-zinc-300">
              If you came for ChatGPT Images 2.0 / GPT image 2, this is the fastest
              user workflow:
            </p>
            <ul className="mt-4 space-y-2 text-sm leading-relaxed text-zinc-400">
              <li>1) Open generator and write one concrete business outcome.</li>
              <li>2) Generate 3-5 variants and keep only the strongest composition.</li>
              <li>3) Use image-to-prompt to reverse and standardize your winning style.</li>
              <li>4) Apply the final prompt across hero, product, and social formats.</li>
            </ul>
            <div className="mt-5 flex flex-wrap gap-2">
              <Link
                href="/generator"
                className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-medium text-zinc-100 transition-colors hover:bg-white/10"
              >
                <Wand2 className="h-4 w-4" />
                Open GPT Image Generator
              </Link>
              <Link
                href="/image-to-prompt"
                className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-transparent px-4 py-2 text-sm font-medium text-zinc-300 transition-colors hover:bg-white/5 hover:text-zinc-100"
              >
                <Layers className="h-4 w-4" />
                Extract Prompt from Image
              </Link>
            </div>
          </aside>
        </div>
      </section>

      <section className="mx-auto mt-14 w-full max-w-5xl px-4 sm:px-6 md:px-10">
        <div className="rounded-3xl border border-white/10 bg-[#090a10]/75 p-7 md:p-10">
          <h2 className="text-2xl font-medium tracking-tight text-white md:text-3xl">
            FAQ: ChatGPT Images 2.0 and GPT image 2
          </h2>
          <div className="mt-6 space-y-3">
            {FAQ_ITEMS.map((item) => (
              <details
                key={item.question}
                className="rounded-xl border border-white/10 bg-[#07080c]/80 p-4"
              >
                <summary className="cursor-pointer list-none text-sm font-medium text-zinc-100">
                  {item.question}
                </summary>
                <p className="mt-3 text-sm leading-relaxed text-zinc-400">{item.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
